# Generated by Django 3.2.2 on 2021-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name var')),
                ('age', models.IntegerField(verbose_name='integer var')),
                ('country', models.IntegerField(verbose_name='country field')),
            ],
        ),
    ]
