# Generated by Django 3.2.3 on 2021-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='experience',
            field=models.SmallIntegerField(choices=[(0, 'low'), (1, 'moderate'), (2, 'high')], default=0),
        ),
    ]
