# Generated by Django 3.2.3 on 2021-08-01 09:28

from django.db import migrations, models


def ammend_the_data(apps, _):
    Person = apps.get_model('people', 'Person')
    people = Person.objects.all().iterator()

    for person in people:
        fullnamesplit = person.fullname.split(';')
        first_name = fullnamesplit[0].split(':')[1]
        last_name = fullnamesplit[1].split(':')[1]

        informationsplit = person.information.split(';')
        info2 = {}
        for info in informationsplit:
            info3 = info.split(':')
            info2.update({info3[0] : info3[1]})
        
        person.first_name = first_name
        person.last_name = last_name
        person.id_code = info2.get('id_code')
        person.born_in = info2.get('born_in')
        person.birth_year = int(info2.get('birth_year'))
        person.save()



class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code= ammend_the_data,
            reverse_code=migrations.RunPython.noop),
        
        migrations.AlterField(
            model_name= 'Person', 
            name= 'first_name',
            field= models.CharField(max_length= 30)),
        migrations.AlterField(
            model_name= 'Person', 
            name= 'last_name',
            field= models.CharField(max_length= 50)),
        migrations.AlterField(
            model_name= 'Person', 
            name= 'id_code',
            field= models.CharField(max_length= 10)),
        migrations.AlterField(
            model_name= 'Person', 
            name= 'born_in',
            field= models.CharField(max_length= 30)),
        migrations.AlterField(
            model_name= 'Person', 
            name= 'birth_year',
            field= models.PositiveSmallIntegerField()),
        
        migrations.RemoveField(
            model_name= 'Person',
            name= 'fullname'),
        migrations.RemoveField(
            model_name= 'Person',
            name= 'information'),
    ]
