# Generated by Django 3.2.3 on 2021-06-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
