# Generated by Django 3.0.6 on 2020-05-31 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='9T Pro', max_length=32)),
                ('price', models.PositiveIntegerField(default=2097152)),
                ('color', models.CharField(default='Black', max_length=16)),
                ('display_size', models.SmallIntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.Brand')),
            ],
        ),
    ]
